### ISSUE TITLE
Bard requires an extra click on "send"

### ISSUE THREAD

**Issue by user41pp** [smol-ai/menubar#65]
I'm on Windows. Installation went without issues. Hitting CMD + enter submits messages to ChatGPT / Bing, but for Bard, I have to click on "send" additionally. The prompt itself is synchronized. How to fix?

Can't test Claude v2 since I'm in europe.

**Comment by swyxio** [comment]
@user41pp thanks for the feedback! this is usually due to some unanticipated issue with the way we use js to find the selector: https://github.com/smol-ai/menubar/blob/e18cdcc6a72658a9c9ea769f707d7f3c97068f36/providers/bard.js#L33  . as you might imagine it sometimes breaks without warning or there are states that we didnt account for in our testing.

 if you want to try taking a stab, run this project locally and pull up the dev tools (its tricky i know but can be done, just do the zoom out thing) and see where it is going wrong.  if not, we'll probably get to it at some point

**Comment by swyxio** [comment]
i think we have fixed this, pls reopen if still a n issue
